name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: yarn install

      - name: Debug Firebase Secrets
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: |
          echo "Checking Firebase configuration..."
          echo "FIREBASE_API_KEY: ${FIREBASE_API_KEY:+set}"
          echo "FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN:+set}"
          echo "FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID:+set}"
          echo "FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET:+set}"
          echo "FIREBASE_MESSAGING_SENDER_ID: ${FIREBASE_MESSAGING_SENDER_ID:+set}"
          echo "FIREBASE_APP_ID: ${FIREBASE_APP_ID:+set}"

      - name: Build
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: yarn build

      - name: Verify Build Output
        run: |
          echo "Checking for Firebase configuration in build output..."
          echo "Looking in JavaScript files..."
          find out -type f -name "*.js" -exec grep -l "firebaseConfig\|FIREBASE\|firebase" {} \;
          
          echo "\nChecking specific Firebase values..."
          if find out -type f -name "*.js" -exec grep -l "apiKey\|projectId\|messagingSenderId" {} \; | grep -q .; then
            echo "Found Firebase configuration values in build output"
          else
            echo "Warning: No Firebase configuration values found in build output"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          force_orphan: true
          commit_message: "deploy: ${{ github.sha }}"

      - name: Verify Deployment
        run: |
          echo "Waiting for deployment to complete..."
          sleep 30
          echo "Checking deployment status..."
          curl -s https://lukefrake.github.io/pokemon-card-tracker/ | grep -q "Pokemon Card Tracker" || exit 1 